### ISSUE TITLE
Outlines can sometimes layer over White/Extra Portions of Icons

### ISSUE THREAD

**Issue by Minemaker0430** [Alphalaneous/FineOutline#1]
![image](https://github.com/user-attachments/assets/00d01600-cb2c-4635-b791-49a33cb8fca5)
The otter icon is made by me (texture pack), the rest is base game/more icons.

![image](https://github.com/user-attachments/assets/cf0f0dc2-a525-468f-ae41-239283c7a65d)
![image](https://github.com/user-attachments/assets/d77d9bf4-7cad-45ba-beb3-6c7805808c7e)
You can see here the white portion meant to be in front is behind it instead.

**Comment by Alphalaneous** [comment]
Resolved in latest update!
